"""
combine_glb_meshes.py
---------------------
Step 2 of the 3-stage STEP-to-GLB processing pipeline.

Responsibilities:
  1. Reads GLB files generated by `step_to_glb.py`.
  2. Cleans node names (strips OCCT tags like '[NAUO1]' or sub-part numbers like '_1').
  3. Combines all sub-primitives / sub-solids of each component (e.g., all 1..13 sub-parts
     of an elbow) into a single unified mesh for that component.
  4. Filters out internal construction geometry (`Part*` nodes) by default.
  5. Saves the consolidated GLB files back in-place.

Usage:
  python combine_glb_meshes.py
  python combine_glb_meshes.py --keep-parts
"""

import re
import argparse
import numpy as np
import pygltflib
from pathlib import Path

BASE_DIR = Path(__file__).parent
DEFAULT_GLB_DIR  = BASE_DIR / "GLB" / "PL" / "Female Wiggins"


def clean_name(name: str) -> str:
    """Clean OCCT tags and trailing sub-mesh suffixes from part names."""
    if not name:
        return "unnamed"
    # Remove OCCT instance tags like [NAUO1]
    name = re.sub(r'\s*\[NAUO\d+\]', '', name).strip()
    # Strip trailing sub-mesh digits like _1, _2, _13
    name = re.sub(r'_\d+$', '', name).strip()
    return name


def is_part_node(name: str) -> bool:
    """Check if node is a generic internal OCCT construction geometry part (starts with Part)."""
    return name.startswith("Part") or "^Part" in name


def get_accessor_array(glb: pygltflib.GLTF2, accessor_idx: int) -> np.ndarray:
    """Extract numeric array from a glTF accessor."""
    if accessor_idx is None:
        return None
    acc = glb.accessors[accessor_idx]
    bv = glb.bufferViews[acc.bufferView]
    raw_data = glb.binary_blob()
    start = (bv.byteOffset or 0) + (acc.byteOffset or 0)
    
    dtype_map = {
        5120: np.int8,
        5121: np.uint8,
        5122: np.int16,
        5123: np.uint16,
        5125: np.uint32,
        5126: np.float32,
    }
    type_size = {
        'SCALAR': 1,
        'VEC2': 2,
        'VEC3': 3,
        'VEC4': 4,
        'MAT4': 16,
    }
    
    dt = dtype_map[acc.componentType]
    count = acc.count * type_size[acc.type]
    data = np.frombuffer(raw_data, dtype=dt, count=count, offset=start)
    if type_size[acc.type] > 1:
        data = data.reshape(-1, type_size[acc.type])
    return data.copy()


def combine_glb_file(glb_path: Path, keep_parts: bool = False) -> bool:
    """
    Combines sub-primitives/meshes of each component in a GLB file into single meshes.
    """
    try:
        glb = pygltflib.GLTF2().load(str(glb_path))
    except Exception as e:
        print(f"  ERROR loading '{glb_path.name}': {e}")
        return False

    if not glb.nodes:
        print(f"  [SKIP] '{glb_path.name}': No nodes found.")
        return False

    # 1. Clean names and collect component nodes
    valid_nodes = []
    
    for idx, node in enumerate(glb.nodes):
        raw_name = node.name or ""
        cleaned = clean_name(raw_name)
        node.name = cleaned
        
        # Filter Part* construction nodes unless keep_parts is True
        if not keep_parts and is_part_node(cleaned):
            continue
            
        if node.mesh is not None:
            valid_nodes.append((idx, node, cleaned))

    if not valid_nodes:
        print(f"  [SKIP] '{glb_path.name}': No component meshes remaining after filtering.")
        return False

    # 2. Rebuild combined GLB with 1 merged mesh per component
    new_glb = pygltflib.GLTF2()
    new_glb.asset = glb.asset
    
    # Root scene node
    root_node_name = glb_path.stem
    root_node = pygltflib.Node(name=root_node_name, children=[])
    new_glb.nodes.append(root_node)
    
    scene = pygltflib.Scene(nodes=[0])
    new_glb.scenes.append(scene)
    new_glb.scene = 0

    new_buffer_bytes = bytearray()
    
    for _, orig_node, comp_name in valid_nodes:
        mesh_obj = glb.meshes[orig_node.mesh]
        
        all_positions = []
        all_normals = []
        all_indices = []
        vertex_offset = 0

        for prim in mesh_obj.primitives:
            pos = get_accessor_array(glb, prim.attributes.POSITION)
            norm = get_accessor_array(glb, prim.attributes.NORMAL)
            idx_arr = get_accessor_array(glb, prim.indices)

            if pos is None or len(pos) == 0:
                continue

            all_positions.append(pos)
            if norm is not None and len(norm) == len(pos):
                all_normals.append(norm)
                
            if idx_arr is not None:
                all_indices.append(idx_arr.astype(np.uint32) + vertex_offset)
            else:
                all_indices.append(np.arange(vertex_offset, vertex_offset + len(pos), dtype=np.uint32))
                
            vertex_offset += len(pos)

        if not all_positions:
            continue

        comp_pos = np.vstack(all_positions).astype(np.float32)
        comp_norm = np.vstack(all_normals).astype(np.float32) if all_normals else None
        comp_indices = np.concatenate(all_indices).astype(np.uint32)

        # --- Create binary buffers & accessors for combined mesh ---
        # 1. POSITION
        pos_bytes = comp_pos.tobytes()
        pos_bv_idx = len(new_glb.bufferViews)
        new_glb.bufferViews.append(pygltflib.BufferView(
            buffer=0,
            byteOffset=len(new_buffer_bytes),
            byteLength=len(pos_bytes),
            target=pygltflib.ARRAY_BUFFER
        ))
        new_buffer_bytes.extend(pos_bytes)
        
        pos_acc_idx = len(new_glb.accessors)
        new_glb.accessors.append(pygltflib.Accessor(
            bufferView=pos_bv_idx,
            byteOffset=0,
            componentType=pygltflib.FLOAT,
            count=len(comp_pos),
            type=pygltflib.VEC3,
            min=comp_pos.min(axis=0).tolist(),
            max=comp_pos.max(axis=0).tolist()
        ))

        # 2. NORMAL
        norm_acc_idx = None
        if comp_norm is not None:
            norm_bytes = comp_norm.tobytes()
            norm_bv_idx = len(new_glb.bufferViews)
            new_glb.bufferViews.append(pygltflib.BufferView(
                buffer=0,
                byteOffset=len(new_buffer_bytes),
                byteLength=len(norm_bytes),
                target=pygltflib.ARRAY_BUFFER
            ))
            new_buffer_bytes.extend(norm_bytes)
            
            norm_acc_idx = len(new_glb.accessors)
            new_glb.accessors.append(pygltflib.Accessor(
                bufferView=norm_bv_idx,
                byteOffset=0,
                componentType=pygltflib.FLOAT,
                count=len(comp_norm),
                type=pygltflib.VEC3
            ))

        # 3. INDICES
        idx_bytes = comp_indices.tobytes()
        idx_bv_idx = len(new_glb.bufferViews)
        new_glb.bufferViews.append(pygltflib.BufferView(
            buffer=0,
            byteOffset=len(new_buffer_bytes),
            byteLength=len(idx_bytes),
            target=pygltflib.ELEMENT_ARRAY_BUFFER
        ))
        new_buffer_bytes.extend(idx_bytes)
        
        idx_acc_idx = len(new_glb.accessors)
        new_glb.accessors.append(pygltflib.Accessor(
            bufferView=idx_bv_idx,
            byteOffset=0,
            componentType=pygltflib.UNSIGNED_INT,
            count=len(comp_indices),
            type=pygltflib.SCALAR,
            min=[int(comp_indices.min())],
            max=[int(comp_indices.max())]
        ))

        # 4. Construct single Primitive & Mesh
        attributes = pygltflib.Attributes(POSITION=pos_acc_idx)
        if norm_acc_idx is not None:
            attributes.NORMAL = norm_acc_idx

        primitive = pygltflib.Primitive(
            attributes=attributes,
            indices=idx_acc_idx,
            mode=pygltflib.TRIANGLES
        )

        new_mesh_idx = len(new_glb.meshes)
        new_glb.meshes.append(pygltflib.Mesh(
            name=comp_name,
            primitives=[primitive]
        ))

        # 5. Create Node for component
        child_node_idx = len(new_glb.nodes)
        child_node = pygltflib.Node(
            name=comp_name,
            mesh=new_mesh_idx,
            translation=orig_node.translation,
            rotation=orig_node.rotation,
            scale=orig_node.scale
        )
        new_glb.nodes.append(child_node)
        root_node.children.append(child_node_idx)

    # Attach binary buffer to GLB
    new_glb.buffers.append(pygltflib.Buffer(byteLength=len(new_buffer_bytes)))
    new_glb.set_binary_blob(bytes(new_buffer_bytes))

    new_glb.save(str(glb_path))
    print(f"  [OK] Combined '{glb_path.name}': {len(root_node.children)} component mesh(es).")
    return True


def run_combine(keep_parts: bool = False, input_dir: Path = None):
    glb_dir = input_dir if input_dir else DEFAULT_GLB_DIR
    glb_files = sorted(glb_dir.glob("*.glb"))
    if not glb_files:
        print(f"No .glb files found in {glb_dir}")
        return

    print(f"Found {len(glb_files)} GLB file(s) in {glb_dir}\n")
    for glb_path in glb_files:
        print(f"Combining meshes for: {glb_path.name}")
        combine_glb_file(glb_path, keep_parts=keep_parts)
        print()

    print("Step 2 Complete: Component sub-meshes combined into single meshes per part.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Combine sub-meshes/primitives of GLB components.")
    parser.add_argument("--keep-parts", action="store_true", help="Keep Part* construction nodes.")
    parser.add_argument("--input-dir", type=str, help="Path to a custom directory containing GLB files.")
    args = parser.parse_args()
    
    input_path = Path(args.input_dir) if args.input_dir else None
    run_combine(keep_parts=args.keep_parts, input_dir=input_path)
